name = "contact-form"
type = "javascript"
route = 'malts.me/contact'
zone_id = '2ba889cd72f0b6627efec7c20b8ce128'
usage_model = ''
workers_dev = false
compatibility_flags = []
compatibility_date = "2022-05-14"

account_id = "fe0bb6cdd07ac12356c63964b0307cdd"

kv_namespaces = [
  { binding = "CONTACT_FORM", preview_id = "6f646952c1004b6394955ab3da88327a", id = "0b2d1c170d3f444188263feef2607724" }
]

[build]
command = "npm run build"
[build.upload]
format = "service-worker"